更新编译开启LOG_NDEBUG

diff --git a/TmakeChenyee b/TmakeChenyee
--- a/TmakeChenyee
+++ b/TmakeChenyee
@@ -114,7 +114,12 @@ error(){
     local ret="$1";shift
     local info="$@"
     if [ "$ret" -ne 0 ];then
-        echo "Error $ret: $info" >&2
+        echo -e "\033[31m[${FUNCNAME[1]}: "`caller 0 | cut -d " " -f 1`"] Error $ret: $info\033[0m" >&2
+        echo "*********************************************************************************"
+        echo "************************build error check keywords begin　************************"
+        grep -rn -E "^ERROR\: |^FATAL\: |^FAILED\: |^Error\:|\: \*\*\* |\: error\: " ${LOGPATH}
+        echo "************************ build error check keywords end 　************************"
+        echo "*********************************************************************************"
         exit $ret
     fi
 }
@@ -132,7 +137,7 @@ get_opts(){
         echo $@
     fi
 
-    opts=$(getopt -o cChi:kslnp:P:rqatv:S:f:m: --long copy_target,copy_chenyee,help,image:,key,sign,listp,new,project:,PROJECT:,remake,remake_billy,tee,target_build_variant:,clear_ccache,sonar:,file_script:,mp_status:,  -- "$@")     
+    opts=$(getopt -o cChHi:kslnp:P:rqatv:S:f:m: --long history, --long copy_target,copy_chenyee,help,image:,key,sign,listp,new,project:,PROJECT:,remake,remake_billy,tee,target_build_variant:,clear_ccache,sonar:,file_script:,mp_status:,  -- "$@")     
     if [ $? -ne 0 ];then
         echo "***$? ***"
         usage 
@@ -196,7 +201,10 @@ get_opts(){
             --clear_ccache)
                 export CY_CLEAN_CCACHE="true"
                 shift 
-                ;;
+		;;
+            -H|--history)
+                show_build_history
+                exit 0 ;;
             -k|--key)
                 ACTION=key
                 shift 
@@ -373,33 +381,21 @@ prebuild(){
 }
 
 replece_sign_key(){
-    if [ -z "${CY_WITH_CUSTOM_SIGNKEY}" -o "${CY_WITH_CUSTOM_SIGNKEY}" == "" -o "${CY_WITH_CUSTOM_SIGNKEY}" == "null" ];then
-        if [ "${BUILD_OPTIONS}" == "platform" -o "${TARGET_BUILD_VARIANT}" != "user" ];then
-            echo "BUILD_OPTIONS=${BUILD_OPTIONS}"
-            echo "TARGET_BUILD_VARIANT=${TARGET_BUILD_VARIANT}"
-        else
-            CY_SIGN_KEY_FOLDER="$HOME/singkey/cykey"
-            if [ "${CY_CUSTOM_SIGN_KEY}" != "" ];then
-                CY_SIGN_KEY_FOLDER="$HOME/singkey/${CY_CUSTOM_SIGN_KEY}"
-            fi
-            if [ -d "${CY_SIGN_KEY_FOLDER}" ];then
-                cp -f ${CY_SIGN_KEY_FOLDER}/* "build/make/target/product/security"
-                echo "copy $CY_SIGN_KEY_FOLDER to  build/make/target/product/security"
-                cp -f ${CY_SIGN_KEY_FOLDER}/* "device/mediatek/security"
-                echo "copy $CY_SIGN_KEY_FOLDER to  device/mediatek/security"
-            else
-                echo "NO ${CY_SIGN_KEY_FOLDER}"
-            fi 
-        fi
+    if [ "${BUILD_OPTIONS}" == "platform" -o "${TARGET_BUILD_VARIANT}" != "user" ];then
+        echo "BUILD_OPTIONS=${BUILD_OPTIONS}"
+        echo "TARGET_BUILD_VARIANT=${TARGET_BUILD_VARIANT}"
     else
-        CY_CUSTOM_SIGN_KEY_FOLDER="$CY_BUILD_ROOT_DIR/cy_project/tools/singkey/$CY_WITH_CUSTOM_SIGNKEY"
-        if [ -d "${CY_CUSTOM_SIGN_KEY_FOLDER}" ];then
-            cp -f ${CY_CUSTOM_SIGN_KEY_FOLDER}/* "build/make/target/product/security"
-            echo "copy $CY_CUSTOM_SIGN_KEY_FOLDER to  build/make/target/product/security"
-            cp -f ${CY_CUSTOM_SIGN_KEY_FOLDER}/* "device/mediatek/security"
-            echo "copy $CY_CUSTOM_SIGN_KEY_FOLDER to  device/mediatek/security"
+        CY_SIGN_KEY_FOLDER="$HOME/singkey/cykey"
+        if [ "${CY_CUSTOM_SIGN_KEY}" != "" ];then
+            CY_SIGN_KEY_FOLDER="$HOME/singkey/${CY_CUSTOM_SIGN_KEY}"
+        fi
+        if [ -d "${CY_SIGN_KEY_FOLDER}" ];then
+            cp -f ${CY_SIGN_KEY_FOLDER}/* "build/make/target/product/security"
+            echo "copy $CY_SIGN_KEY_FOLDER to  build/make/target/product/security"
+            cp -f ${CY_SIGN_KEY_FOLDER}/* "device/mediatek/security"
+            echo "copy $CY_SIGN_KEY_FOLDER to  device/mediatek/security"
         else
-            echo "NO ${CY_CUSTOM_SIGN_KEY_FOLDER}"
+            echo "NO ${CY_SIGN_KEY_FOLDER}"
         fi 
     fi
 }
@@ -417,6 +413,16 @@ get_chenyee_code(){
     sed -i "s/^\s*MTK_BUILD_VERNO\s*=\s*.*/MTK_BUILD_VERNO=${CY_ZNVERNUMBER}/"  ${CY_PRODUCT_FILE}
     echo 'MTK_BUILD_VERNO='$(cat ${CY_PRODUCT_FILE} | grep "^\s*MTK_BUILD_VERNO" | sed 's/.*\s*=\s*//g')
     #Chenyee sunll 2015-01-21 modify MTK_BUILD_VERNO=${CY_ZNVERNUMBER} end
+}
+
+enable_kernel_debug_config()
+{
+    grep "CONFIG_DEBUG_PINCTRL=y" $CY_KERNEL_CFG_FILE > /dev/null
+    if [ $? -eq 0 ]; then
+        echo "kernel DEBUG已经修改过，不用修改"
+    else
+        echo "CONFIG_DEBUG_PINCTRL=y" >> $CY_KERNEL_CFG_FILE
+    fi
 }
 
 set_kernel_config(){
@@ -470,6 +476,7 @@ set_kernel_config(){
                 fi
             fi
         done < <(env)
+        enable_kernel_debug_config
     else
         echo "kernel config file: $CY_KERNEL_CFG_FILE not exist"
     fi
@@ -486,11 +493,7 @@ get_release_version(){
 
 create_product_for_flash_tool(){
     if [ -e "./cy_project/tools/cy_output_product_info.sh" ];then
-        if [ "${CHENYEEPROJECTID}" == "SW17W13" ];then
-            bash ./cy_project/tools/gn_output_product_info.sh ${CHENYEEPRODUCTID} ${CY_RELEASE_DIR}
-        else
-            bash ./cy_project/tools/cy_output_product_info.sh ${CHENYEEPRODUCTID} ${CY_RELEASE_DIR}
-        fi
+        bash ./cy_project/tools/cy_output_product_info.sh ${CHENYEEPRODUCTID} ${CY_RELEASE_DIR}
     fi
 }
 
@@ -623,13 +626,11 @@ copy_results_to_release(){
         rm -rf $CY_RELEASE_OTA_DIR_ROOT
         mkdir -p $CY_RELEASE_OTA_TMP_DIR
         mkdir -p $CY_RELEASE_OTA_DIR
-        CY_RO_BUILD_DISPLAY_ID_TMP=$(echo ${CY_RO_BUILD_DISPLAY_ID})
-        CY_RO_BUILD_DISPLAY_ID_TMP=`echo ${CY_RO_BUILD_DISPLAY_ID_TMP} | sed 's/ /_/'`
-        cp -r $ota_zip $CY_RELEASE_OTA_DIR/${CHENYEEPRODUCTID}_update_${CY_RO_BUILD_DISPLAY_ID_TMP}_${MINI_VER_NUMBER}.zip
-        local ota_md5=$(md5sum $CY_RELEASE_OTA_DIR/${CHENYEEPRODUCTID}_update_${CY_RO_BUILD_DISPLAY_ID_TMP}_${MINI_VER_NUMBER}.zip |awk '{print $1}')
-        echo "${CHENYEEPRODUCTID}_update_${CY_RO_BUILD_DISPLAY_ID_TMP}_${MINI_VER_NUMBER}.zip=$ota_md5" > $CY_RELEASE_OTA_DIR/${CHENYEEPRODUCTID}_${MINI_VER_NUMBER}.md5
-        cp -r $ota_tmp_zip $CY_RELEASE_OTA_TMP_DIR/${CHENYEEPRODUCTID}_update_${CY_RO_BUILD_DISPLAY_ID_TMP}_${MINI_VER_NUMBER}_tmp.zip
-        #Chenyee <CY_3rd> <lucy> <20180306> for CSW1703MX-9 beign
+        cp -r $ota_zip $CY_RELEASE_OTA_DIR/${CHENYEEPRODUCTID}_update_${CY_RO_BUILD_DISPLAY_ID}_${MINI_VER_NUMBER}.zip
+        local ota_md5=$(md5sum $CY_RELEASE_OTA_DIR/${CHENYEEPRODUCTID}_update_${CY_RO_BUILD_DISPLAY_ID}_${MINI_VER_NUMBER}.zip |awk '{print $1}')
+        echo "${CHENYEEPRODUCTID}_update_${CY_RO_BUILD_DISPLAY_ID}_${MINI_VER_NUMBER}.zip=$ota_md5" > $CY_RELEASE_OTA_DIR/${CHENYEEPRODUCTID}_${MINI_VER_NUMBER}.md5
+        cp -r $ota_tmp_zip $CY_RELEASE_OTA_TMP_DIR/${CHENYEEPRODUCTID}_update_${CY_RO_BUILD_DISPLAY_ID}_${MINI_VER_NUMBER}_tmp.zip
+#Chenyee <CY_3rd> <lucy> <20180306> for CSW1703MX-9 beign
         if [ "${ADUPS_FOTA_SUPPORT}" == "yes" ];then
             if [ "${ADUPS_FOTA_SIGINATURE}" == "yes" ];then
                 mkdir -p ${CY_RELEASE_OTA_DIR_ROOT}/3rd
@@ -639,6 +640,13 @@ copy_results_to_release(){
             fi           
         fi
 #Chenyee <CY_3rd> <lucy> <20180306> for CSW1703MX-9 end
+	 #Chenyee <CY_REQ> <huangxiaohong> <20180808> for CSW1703IC-92 beign
+        if [ "${REDSTONE_FOTA_SUPPORT}" == "yes" ];then
+                mkdir -p ${CY_RELEASE_OTA_DIR_ROOT}/3rd
+                cp -f ${TARGET_PRODUCT_OUT_ROOT}/rsfota_target_files-package.zip ${CY_RELEASE_OTA_DIR_ROOT}/3rd/;
+                #cp -f ${TARGET_PRODUCT_OUT_ROOT}/target_files-package.zip $CY_RELEASE_OTA_DIR/;           
+        fi
+        #Chenyee <CY_REQ> <huangxiaohong> <20180808> for CSW1703IC-92 end
     fi
     if [ ! -e "$TARGET_PRODUCT_OUT_ROOT/system.img" ];then
         echo "你的编译结果不完全，请查看是否编译成功。"
@@ -742,6 +750,9 @@ build_remake(){
     build_update_api
     fix_build_err
     enable_AudPar
+    enable_audio_debug
+    change_MMI_packages
+    disable_dreams
     build_android
     build_copy_target
 }
@@ -753,6 +764,8 @@ build_remake_billy(){
     enable_AudPar
     enable_audio_debug
     #dump_stack
+    change_MMI_packages
+    disable_dreams
     build_android
     #build_copy_target
 }
@@ -831,7 +844,7 @@ dump_stack()
     if [ $? -eq 0 ]; then
             echo "已经修改过，不用修改"
     else
-        sed -i 's/ensureValidDirection(direction);/Log.e(TAG, "billy:" + Log.getStackTraceString(new Throwable()));\n\\t\t&/' $AudioService
+        sed -i 's/ensureValidDirection(direction);/Log.e(TAG, "billy:" + Log.getStackTraceString(new Throwable()));\n\t\t&/' $AudioService
         sed -i 's/ensureValidDirection(direction);/RuntimeException re = new RuntimeException();\n\t\t\t\tre.fillInStackTrace();\n\t\t\t\tLog.d(TAG, "billy", re);\n\t\t&/' $AudioService
     fi
 }
@@ -869,17 +882,21 @@ enable_audio_debug()
     AudioJniDir=$CY_BUILD_ROOT_DIR/frameworks/base/core/jni
     AudioFlinger=$CY_BUILD_ROOT_DIR/frameworks/av/services/audioflinger
     AudioPolicy=$CY_BUILD_ROOT_DIR/frameworks/av/services/audiopolicy
+    MediaExtractor=$CY_BUILD_ROOT_DIR/frameworks/av/services/mediaextractor
+    MediaJniDir=$CY_BUILD_ROOT_DIR/frameworks/base/media/jni
     Media=$CY_BUILD_ROOT_DIR/frameworks/av/media
 
+    android_media_MediaDrm=$MediaJniDir/android_media_MediaDrm.cpp
     AudioStreamInternal=$Media/libaaudio/src/client/AudioStreamInternal.cpp
     AudioStreamInternalCapture=$Media/libaaudio/src/client/AudioStreamInternalCapture.cpp
     AudioStreamInternalPlay=$Media/libaaudio/src/client/AudioStreamInternalPlay.cpp
-    MonoPipeReader=$Media/frameworks/av/media/libnbaio/MonoPipeReader.cpp
-    MonoPipe=$Media/frameworks/av/media/libnbaio/MonoPipe.cpp
-    Pipe=$Media/frameworks/av/media/libnbaio/Pipe.cpp
-    PipeReader=$Media/frameworks/av/media/libnbaio/PipeReader.cpp
+    MonoPipeReader=$Media/libnbaio/MonoPipeReader.cpp
+    MonoPipe=$Media/libnbaio/MonoPipe.cpp
+    Pipe=$Media/libnbaio/Pipe.cpp
+    PipeReader=$Media/libnbaio/PipeReader.cpp
 
-    AudioMixer=$CY_BUILD_ROOT_DIR/frameworks/av/media/libaudioprocessing/AudioMixer.cpp
+    AudioMixer=$Media/libaudioprocessing/AudioMixer.cpp
+    SpeechType=$CY_BUILD_ROOT_DIR/vendor/mediatek/proprietary/hardware/audio/common/include/SpeechType.h
 
     grep "#define LOG_NDEBUG 0 //billy" $AudioMixer > /dev/null
     if [ $? -eq 0 ]; then
@@ -888,9 +905,12 @@ enable_audio_debug()
         scandir $AudioJniDir
         scandir $AudioFlinger
         scandir $AudioPolicy
+        scandir $MediaExtractor
+        scandir $MediaJniDir
         scandir $Media
 
-        sed -i 's/i);/name\/*billy*\/);/g' $AudioMixer
+        #sed -i 's/ i);/name\/*billy*\/);/g' $AudioMixer
+        sed -i 's/#define LOG_NDEBUG 0 \/\/billy/\/\/#define LOG_NDEBUG 0 \/\/billy/g' $android_media_MediaDrm
         sed -i 's/#define LOG_NDEBUG 0 \/\/billy/\/\/#define LOG_NDEBUG 0 \/\/billy/g' $AudioStreamInternal
         sed -i 's/#define LOG_NDEBUG 0 \/\/billy/\/\/#define LOG_NDEBUG 0 \/\/billy/g' $AudioStreamInternalCapture
         sed -i 's/#define LOG_NDEBUG 0 \/\/billy/\/\/#define LOG_NDEBUG 0 \/\/billy/g' $AudioStreamInternalPlay
@@ -898,19 +918,56 @@ enable_audio_debug()
         sed -i 's/#define LOG_NDEBUG 0 \/\/billy/\/\/#define LOG_NDEBUG 0 \/\/billy/g' $MonoPipe
         sed -i 's/#define LOG_NDEBUG 0 \/\/billy/\/\/#define LOG_NDEBUG 0 \/\/billy/g' $Pipe
         sed -i 's/#define LOG_NDEBUG 0 \/\/billy/\/\/#define LOG_NDEBUG 0 \/\/billy/g' $PipeReader
+        sed -i 's/#if 0 \/\/ for/#if 1 \/\/ billy for/g' $SpeechType
 
         cd $cur_dir
     fi
 
 }
 
+disable_dreams()
+{
+    enableKeyguardService_config=$CY_BUILD_ROOT_DIR/frameworks/base/packages/SystemUI/res/values/config.xml
+    dreams_config=$CY_BUILD_ROOT_DIR/frameworks/base/core/res/res/values/config.xml
+    defaults_values=$CY_BUILD_ROOT_DIR/frameworks/base/packages/SettingsProvider/res/values/defaults.xml
+    PowerManagerService=$CY_BUILD_ROOT_DIR/frameworks/base/services/core/java/com/android/server/power/PowerManagerService.java
+    
+    grep "name=\"config_dreamsEnabledByDefault\">false" $dreams_config > /dev/null
+        if [ $? -eq 0 ]; then
+        echo "已经修改过，不用修改"
+    else
+        sed -i 's/name=\"config_enableKeyguardService\">true/name=\"config_enableKeyguardService\">false/g' $enableKeyguardService_config
+        sed -i 's/bool name=\"config_dreamsSupported\">true/bool name=\"config_dreamsSupported\">false/g' $dreams_config
+        sed -i 's/name=\"config_dreamsEnabledByDefault\">true/name=\"config_dreamsEnabledByDefault\">false/g' $dreams_config
+        sed -i 's/name=\"def_lockscreen_disabled\">false/name=\"def_lockscreen_disabled\">true/g' $defaults_values
+        sed -i '/goToSleep(long/a\\t\t\tif (true){ return; }' $PowerManagerService
+    fi
+}
+
+change_MMI_packages()
+{
+    if [ -d $CY_BUILD_ROOT_DIR/packages/apps/CY_MMI_old ];then
+        echo "已经替换过了，不用再替换"
+    else
+        mv $CY_BUILD_ROOT_DIR/packages/apps/CY_MMI/Android.mk $CY_BUILD_ROOT_DIR/packages/apps/CY_MMI/Android.mk.bak
+        mv $CY_BUILD_ROOT_DIR/packages/apps/CY_MMI $CY_BUILD_ROOT_DIR/packages/apps/CY_MMI_old
+        ln -s ~/bin/shell_test/package/CY_MMI/OM8.0 $CY_BUILD_ROOT_DIR/packages/apps/CY_MMI
+
+        mv $CY_BUILD_ROOT_DIR/packages/apps/CY_AutoMMI/Android.mk $CY_BUILD_ROOT_DIR/packages/apps/CY_AutoMMI/Android.mk.bak
+        mv $CY_BUILD_ROOT_DIR/packages/apps/CY_AutoMMI $CY_BUILD_ROOT_DIR/packages/apps/CY_AutoMMI_old
+        ln -s ~/bin/shell_test/package/CY_AutoMMI/OM8.0 $CY_BUILD_ROOT_DIR/packages/apps/CY_AutoMMI
+    fi
+}
+
 build_new(){
     build_clean
     build_copy_cy_code
-    build_err
+    fix_build_err
     enable_AudPar
     enable_audio_debug
     #dump_stack
+    change_MMI_packages
+    disable_dreams
     build_remake
     create_check_list
     release_kernel_binary
@@ -928,6 +985,7 @@ build_sign(){
 }
 
 build_project(){
+    speedup_set_state "modified"
     local project_path=$1
     if [ "$CMD_MMM" = "true" ]; then
         $BUILD_TOOLS --build_variant $TARGET_BUILD_VARIANT --PROJECT $project_path $TARGET_PRODUCT  --log_file $LOGPATH/$TARGET_PRODUCT-mmm
@@ -972,8 +1030,78 @@ check_external_iw_version_sh(){
     fi
 }
 
+setup_speedup(){
+    [ ! -e $SPEEDUP_PATH ] && mkdir -p $SPEEDUP_PATH
+}
+
+is_speedup_support(){
+    # DO NOT enable this feature on build server.
+    if $IS_SERVER_BUILD; then
+        echo false; return 1
+    fi
+
+    if [ "$CHENYEE_SPEEDUP_FEATURE" == "false" ]; then
+        echo false; return 1
+    fi
+
+    # DO NOT enable this feature if repo's version is not matching the shell script.
+    if [ ! -f $CY_BUILD_ROOT_DIR/../.repo/repo/subcmds/state.py ]; then
+        echo false; return 1
+    fi
+
+    # DO NOT enable this feature on old brunch.
+    if [ -f $CY_BUILD_ROOT_DIR/cy_tools/cy_speedup_flag ]; then
+        echo true;  return 0
+    else
+        echo false; return 1
+    fi
+}
+
+speedup_get_state(){
+    if [ $(is_speedup_support) == "false" ]; then
+        echo false; return 1 
+    fi
+
+    if [ x"$1" == x"block" ]; then
+        { flock -e 7; cat $SPEEDUP_STATE; flock -u 7; } 7<>"$SPEEDUP_STATE"
+    else
+        cat $SPEEDUP_STATE
+    fi
+}
+
+speedup_set_state(){
+    if [ $(is_speedup_support) == "false" ]; then
+        echo false; return 1
+    else
+        { flock -e 7; echo $1 > $SPEEDUP_STATE; flock -u 7; } 7<>"$SPEEDUP_STATE"
+    fi
+}
+
+store_build_history(){
+    local dline="==========================="
+    local record=`date +"%Y.%m.%d-%H:%M:%S"`"    $@"
+
+    [ ! -e $SPEEDUP_PATH/.history ] && echo "$dline END $dline" > $SPEEDUP_PATH/.history
+    sed -i "1i\\$record" $SPEEDUP_PATH/.history
+    echo $CHENYEEPRODUCTID > $SPEEDUP_PATH/.build_product
+    echo $TARGET_BUILD_VARIANT > $SPEEDUP_PATH/.build_variant
+}
+
+show_build_history(){
+    [ ! -e $SPEEDUP_PATH/.history ] && error 1 "NO BUILD HISTORY!"
+    local dline="========================="
+    echo -e "\033[1mThe Last Command:"
+    echo -e "$(head -n 1 $SPEEDUP_PATH/.history | cut -b 24-)\033[0m\n"
+    echo "$dline"" HISTORY ""$dline"
+    cat $SPEEDUP_PATH/.history
+}
+
 main(){
    get_opts "$@" 
+    setup_speedup
+    store_build_history "$0 $@"
+    #check external/iw/version.sh before build
+    check_external_iw_version_sh
    prebuild
 
    #copy chenyee code
@@ -989,9 +1117,7 @@ main(){
 
    if [ -n "$MODULE" ];then
        echo "********* build $MODULE*********"
-       if [ "$MODULE" != "bootimage" ];then
-           config_verified_boot
-       fi
+       config_verified_boot
        build_module $MODULE
    fi
 
@@ -1025,6 +1151,8 @@ IS_SERVER_BUILD=false
 SHOWLOG=false
 #CY_BUILD_ROOT_DIR=$(cd `dirname $0`; pwd)
 CY_BUILD_ROOT_DIR=$(pwd)
+SPEEDUP_PATH="$CY_BUILD_ROOT_DIR/.speedup"
+SPEEDUP_STATE="$SPEEDUP_PATH/state"
 export CY_BUILD_ROOT_DIR
 GN_BUILD_ROOT_DIR=$CY_BUILD_ROOT_DIR
 export GN_BUILD_ROOT_DIR
